# choose device. if device < 0, so 'cpu' is chosen. Otherwise, it indicates gpu id 
device: 0

# log
logdir: logs/vqvae
max_epoch: 100

# train, test, evaluate
run: test


# random seed
rand_seed: 19

# model config
model:
  in_channels: 3
  out_channels: 3
  channels_list: [64, 128, 256, 512]   # Reference channels of model 
  n_embedding: 512  # Reference value of model 
  d_embedding: 512   # Reference value of model
  beta: 0.25

# dataset
data:
  train:
    root_dir:    # data directory saving training dataset 
    filelist:    # file list of training data
    batch_size: 
    shuffle: True
    num_work: 0
  
  test:
    root_dir:   # data directory saving testing dataset 
    filelist:   # file list of testing data
    batch_size: 
    shuffle: False
    num_work: 0

# dataloader

loader:
  train_batch_size: 25
  test_batch_size: 10
  num_workers: 2



# optimizer
optimizer:
  type: AdamW
  base_lr: 0.0001

# scheuler
scheduler:
  type: StepLR
  gamma: 0.75
  step_size: 1
  
